### ISSUE TITLE
Add project on central maven

### ISSUE THREAD

**Issue by kakawait** [marcosbarbero/spring-cloud-starter-zuul-ratelimit#1]
I didn't find any relative package on maven central. Can be a great addition to add it on maven central in order to easily use this starter

**Comment by marcosbarbero** [comment]
You're right, it's not in central yet. I'll try to promote it asap, once it's done I'll let you know!

**Comment by kakawait** [comment]
I also linked your repo on https://github.com/spring-cloud/spring-cloud-netflix/pull/895. Rate limiting can be  part of next Spring cloud release train.

**Comment by marcosbarbero** [comment]
Thank you! I'll improve tests docs and publish it to maven central. It will help.
The biggest different between this starter to the related PR is the policies improvement, there are more control filtering by service, origin and authenticated user.

**Comment by kakawait** [comment]
Yeah I still prefer your policy (per service) that why I linked your repo to open discussion on maybe future built in support on spring cloud netflix

**Comment by marcosbarbero** [comment]
I'll make a comment in the PR and write down the difference between the implementations

**Comment by marcosbarbero** [comment]
https://issues.sonatype.org/browse/OSSRH-23678

**Comment by marcosbarbero** [comment]
@kakawait here we go! http://search.maven.org/#artifactdetails%7Ccom.marcosbarbero.cloud%7Cspring-cloud-zuul-ratelimit%7C1.0.0.RELEASE%7Cjar if you have any issue let me know

**Comment by kakawait** [comment]
I'm plan to use it in few week. Thank for central maven upload

**Comment by marcosbarbero** [comment]
Sounds great!
