### ISSUE TITLE
Commands not supported in redis cluster

### ISSUE THREAD

**Issue by RichardCSantana** [marcosbarbero/spring-cloud-starter-zuul-ratelimit#3]
The methods multi and exec of class org.springframework.data.redis.core.RedisOperations are not supported in org.springframework.data.redis.connection.jedis.JedisClusterConnection, so it can`t work with redis cluster.

**Comment by marcosbarbero** [comment]
Just released a new version that fix this https://github.com/marcosbarbero/spring-cloud-starter-zuul-ratelimit/releases/tag/v1.0.4.RELEASE
