### ISSUE TITLE
Policies required for every route on gateway

### ISSUE THREAD

**Issue by RichardCSantana** [marcosbarbero/spring-cloud-starter-zuul-ratelimit#4]
The method key make a request for `policy.getTypes()` after `policy()`:
```
final Policy policy = this.policy();		
final Route route = route();
StringBuilder builder = new StringBuilder(route.getId());
if (policy.getType().contains(Policy.Type.ORIGIN)) {
...
if (policy.getType().contains(Policy.Type.USER)) {
...
```

```
private Policy policy() {
    return (route() != null) ? properties.getPolicies().get(route().getId()) : null;
}
```
So its implies that every route under the gateway should have a policy or it will throw a NullPointer.

**Comment by RichardCSantana** [comment]
#https://github.com/marcosbarbero/spring-cloud-starter-zuul-ratelimit/pull/5

**Comment by RichardCSantana** [comment]
#5

**Comment by marcosbarbero** [comment]
Take a look at [v1.0.2.RELEASE](https://github.com/marcosbarbero/spring-cloud-starter-zuul-ratelimit/releases/tag/v1.0.2.RELEASE)
